package com.example.hoopfinder;

import com.google.firebase.database.DatabaseReference;
import com.google.firebase.database.FirebaseDatabase;

/**
 * Controls the structure for app users and allows subscribing users to courts
 */
public class User {
    String user_id;
    String user_email;
    String user_pwd;
    String user_courtsSubscribedTo;
    DatabaseReference db = FirebaseDatabase.getInstance().getReference();

    /**
     * Default constructor for use by Firebase
     */
    public User(){

    }

    /**
     * Constructor for a user
     * @param user_id ID of user automatically generated by registration process
     * @param user_email Email address of user
     * @param user_pwd User's password
     */
    public User(String user_id, String user_email, String user_pwd){
        this.user_id =user_id;
        this.user_pwd = user_pwd;
        this.user_email = user_email;
    }

    /**
     * Constructor for a user
     * @param user_id ID of user automatically generated by registration process
     * @param user_email Email address of user
     * @param user_pwd User's password
     * @param user_courtsSubscribedTo List of courts user is subscribed to
     */
    public User(String user_id, String user_email, String user_pwd, String user_courtsSubscribedTo){
        this.user_id =user_id;
        this.user_pwd = user_pwd;
        this.user_email = user_email;
        this.user_courtsSubscribedTo = user_courtsSubscribedTo;
    }

    /**
     * Subscribes the current user to a court
     * @param courtName The name of the court to subscribe the user to
     * @return boolean true if successful false if unsuccessful
     *
     */
    public boolean subscribeToCourt(String courtName){
        // depending on the implementation of this method, the validity of the court name and format may need to be checked
        user_courtsSubscribedTo += ", " + courtName;
        db.child("User").child(user_id).child("courtsSubscribedTo").setValue(user_courtsSubscribedTo);
        return true;   // ADD RETURN FALSE IF UNSUCCESSFUL
    }


    public String getUser_id() {
        return user_id;
    }

    public String getUser_email() {
        return user_email;
    }

    public String getUser_pwd() {
        return user_pwd;
    }

    public String getCourtsSubscribedTo(){
        return user_courtsSubscribedTo;
    }
}
